name: Python Code Validator CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.11", "3.12" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: Install uv (Windows)
        run: powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
        if: runner.os == 'Windows'

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: Add uv to PATH (Windows)
        run: echo "$((Get-Item (Get-Command uv).Source).Directory.FullName)" | Out-File -FilePath $env:GITHUB_PATH -Append
        if: runner.os == 'Windows'

      - name: Set up Python with uv
        run: uv venv -p ${{ matrix.python-version }}

      - name: Activate venv and Install dependencies
        shell: bash
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Lint and Format with ruff
        shell: bash
        run: |
          source .venv/bin/activate
          ruff check src/ tests/
          ruff format --check src/ tests/

      - name: Run tests with coverage
        shell: bash
        run: |
          source .venv/bin/activate
          coverage run -m unittest discover tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true