name: Python Code Validator CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.11", "3.12" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv venv
          uv pip install -e ".[dev]"

      - name: Run linting and formatting check
        run: .venv/bin/python -m ruff check src/ tests/ && .venv/bin/python -m ruff format --check src/ tests/
        if: runner.os != 'Windows'
      - name: Run linting and formatting check (Windows)
        run: .\.venv\Scripts\python.exe -m ruff check src/ tests/ ; .\.venv\Scripts\python.exe -m ruff format --check src/ tests/
        if: runner.os == 'Windows'

      - name: Run tests and generate coverage report
        run: .venv/bin/python -m coverage run -m unittest discover tests
        if: runner.os != 'Windows'
      - name: Run tests and generate coverage report (Windows)
        run: .\.venv\Scripts\python.exe -m coverage run -m unittest discover tests
        if: runner.os == 'Windows'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true